name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMake configure.
        run: cmake -B build
      - name: CMake build.
        run: cmake --build build
      - name: Run BoseHubbard1D.
        run: build/dmrg examples/bose_hubbard_1d.json
