name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: ${{ matrix.toolchain.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - {
              name: "GCC 8",
              cc: "gcc-8",
              cxx: "g++-8",
              dependencies: "gcc-8 g++-8",
              os: ubuntu-20.04,
            }
          - {
              name: "GCC 9",
              cc: "gcc-9",
              cxx: "g++-9",
              dependencies: "gcc-9 g++-9",
              os: ubuntu-20.04,
            }
          - {
              name: "GCC 10",
              cc: "gcc-10",
              cxx: "g++-10",
              dependencies: "gcc-10 g++-10",
              os: ubuntu-20.04,
            }
          - {
              name: "GCC 11",
              cc: "gcc-11",
              cxx: "g++-11",
              dependencies: "gcc-11 g++-11",
              os: ubuntu-20.04,
            }
          - {
              name: "Clang 6",
              cc: "clang-6.0",
              cxx: "clang++-6.0",
              dependencies: "clang-6.0",
              os: ubuntu-20.04,
            }
          - {
              name: "Clang 7",
              cc: "clang-7",
              cxx: "clang++-7",
              dependencies: "clang-7",
              os: ubuntu-20.04,
            }
          - {
              name: "Clang 8",
              cc: "clang-8",
              cxx: "clang++-8",
              dependencies: "clang-8",
              os: ubuntu-20.04,
            }
          - {
              name: "Clang 9",
              cc: "clang-9",
              cxx: "clang++-9",
              dependencies: "clang-9",
              os: ubuntu-20.04,
            }
          - {
              name: "Clang 10",
              cc: "clang-10",
              cxx: "clang++-10",
              dependencies: "clang-10",
              os: ubuntu-20.04,
            }
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install dependencies.
        run: |
          sudo apt-get update
          sudo apt-get install -yq libboost-all-dev libhdf5-serial-dev
      - name: Install compiler.
        run: sudo apt-get install -yq ${{ matrix.toolchain.dependencies }}
      - name: CMake configure.
        run: CC=${{ matrix.toolchain.cc }} CXX=${{ matrix.toolchain.cxx }} cmake -B build
      - name: CMake build.
        run: cmake --build build
      - name: Run BoseHubbard1D.
        run: build/mpskit dmrg --input examples/bose_hubbard_1d.json --psi dmrg.itensor --output results.h5
      - name: Run IsingLR1D.
        run: build/mpskit dmrg --input examples/ising_lr_1d.json --psi dmrg.itensor --output results.h5
      - name: Run IsingLRSquare.
        run: build/mpskit dmrg --input examples/ising_lr_square.json --psi dmrg.itensor --output results.h5
      - name: Run TransverseIsing1D.
        run: build/mpskit dmrg --input examples/transverse_ising_1d.json --psi dmrg.itensor --output results.h5
      - name: Run TransverseIsingSquare.
        run: build/mpskit dmrg --input examples/transverse_ising_square.json --psi dmrg.itensor --output results.h5
      - name: Run XYSpinGlass1D.
        run: build/mpskit dmrg --input examples/xy_spin_glass_1d.json --psi dmrg.itensor --output results.h5
