name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository.
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: CMake configure.
        run: cmake -B build
      - name: CMake build.
        run: cmake --build build
      - name: Run BoseHubbard1D.
        run: build/dmrg examples/bose_hubbard_1d.json
      - name: Run TransverseIsing1D.
        run: build/dmrg examples/transverse_ising_1d.json
